#page title
page_title                                : KITCraft                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6444695450                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : KITCraft                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Stunning SDK icon generator.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : David Steinacher
your_link                                 :
your_city                                 :
email_address                             :
facebook_username                         :
instagram_username                        :
twitter_username                          : stonko1994
github_username                           : stonko1994
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Stunning icons
    description                           : KITCraft makes it easy to create custom, professional-grade icons for your SDKs.
    fontawesome_icon_name                 : magic

  - title                                 : Customizable
    description                           : Customize colors, sections, images, and use SFSymbols.
    fontawesome_icon_name                 : pen-nib

  - title                                 : Export
    description                           : Export as PNG or JPG
    fontawesome_icon_name                 : file-export



# Theme Settings
topbar_color                              : "#0c0f0a"
topbar_transparency                       : 0.0
topbar_title_color                        : "#ffffff"

cover_image                               : # assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#0c0f0a"

link_color                                : "#009fb7"

app_title_color                           : "#f2edeb"
app_price_color                           : "#f2edeb"
app_description_color                     : "#f2edeb"

feature_title_color                       : "#f2edeb"
feature_text_color                        : "#f2edeb"

feature_icons_foreground_color            : "#009fb7"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
